version: '3'

services:
    app:
        build: .
        ports:
            - "8002:80"
        depends_on:
            - db
    db:
        image: "vinils/mssql-server-windows-developer"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Senh@123"
            ACCEPT_EULA: "Y"
            MSSQL_AGENT_ENABLED: "true"